### ISSUE TITLE
varnish.py giving errors

### ISSUE THREAD

**Issue by xjamundx** [cloudkick/agent-plugins#36]
This is the output when I run varnish.py

```
File "./varnish.py", line 65
     with open(HIT_RATE_FILE, 'r') as f:
        ^
 SyntaxError: invalid syntax
```

My version is 

```
python -V
Python 2.4.3
```

I'm on CentOS 5.5

**Comment by mayur-mq** [comment]
It will work on python 2.7 or higher versions

**Comment by Kami** [comment]
Or you could add `from __future__ import with_statement` to the top (e1075a86c33edba99f7ecaf4820bcf7c9b7e5b83) and it will also work with Python 2.5, but not with 2.4. 2.4 is really ancient.

Edit: Ah, wow, I just noticed this issue is more than 2 years old. I'm closing it since it's not relevant anymore.
